### ISSUE TITLE
   [!] No podspec found for `fc_native_video_thumbnail` in `.symlinks/plugins/fc_native_video_thumbnail/ios`

### ISSUE THREAD

**Issue by linlamlinlam** [flutter-cavalry/fc_native_video_thumbnail#2]
[!] No podspec found for `fc_native_video_thumbnail` in `.symlinks/plugins/fc_native_video_thumbnail/ios`

**Comment by mgenware** [comment]
`v0.7.0` converted ios and macos implementations into a shared codebase. Try `flutter clean` and build again. Feel free to reopen if it's not resolved on your end.
