### ISSUE TITLE
"Operation failed. 'image.Attach' failed with Error 0x80004005" on Windows

### ISSUE THREAD

**Issue by sfabio01** [flutter-cavalry/fc_native_video_thumbnail#3]
I'm getting the following exception when trying to generate a thumbnail on Windows:
"Operation failed. `image.Attach` failed with Error 0x80004005: Unspecified error"

This is my code snippet:
```
try {
  thumbnailGenerated = await plugin.getVideoThumbnail(
      srcFile: result.files.single.path!,
      destFile: thumbpath,
      height: 200,
      width: 200,
      keepAspectRatio: true,
      format: 'jpeg',
      quality: 100);
} catch (e) {
  showGenericErrorToast(
      'Error generating thumbnail: ' + e.toString());
  return;
}
```

**Comment by mgenware** [comment]
hi @sfabio01 , I googled `0x80004005`, it seems to be some access/permission errors. Is it from a network drive (or anything different from an ordinary file)? can you read the src file successfully via dart APIs?
