### ISSUE TITLE
Failed to obtain thumbnails for some videos，errors below

### ISSUE THREAD

**Issue by TogetherShareEachOther** [flutter-cavalry/fc_native_video_thumbnail#8]
1、Error 1：
Error: PlatformException(PluginError, Operation failed. `GetThumbnail` failed with Error 0x8004b200: IDispatch error #45056, null, null)
2、Error 2：
FormatException: Unexpected extension byte (at offset 78)

**Comment by mgenware** [comment]
The Error 0x8004b200 seems to be expected when you open a file that fails to get a thumbnail, for example, an exe file. After v0.11.0, this error is muted on windows, this plug simply returns false instead. If this error happens on a video file that has thumbnail on your explorer, please reopen this issue.
