### ISSUE TITLE
Build on Gradle 8 fails

### ISSUE THREAD

**Issue by birger-ant** [flutter-cavalry/fc_native_video_thumbnail#9]
I've upgraded my flutter project to use APG 8+ and the package fails with following error

Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: C:\Users\<myname>\AppData\Local\Pub\Cache\hosted\pub.dev\fc_native_video_thumbnail-0.9.0\android\build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

**Comment by mgenware** [comment]
v0.15.0 released with gradle 8 support
